/**
 * axxell-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AxxellApi) {
      root.AxxellApi = {};
    }
    root.AxxellApi.Item = factory(root.AxxellApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Item model module.
   * @module model/Item
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Item</code>.
   * An item is often equivalent to a product or service in your store
   * @alias module:model/Item
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>Item</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Item} obj Optional instance to populate.
   * @return {module:model/Item} The populated <code>Item</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('creationTime')) {
        obj['creationTime'] = ApiClient.convertToType(data['creationTime'], 'String');
      }
      if (data.hasOwnProperty('itemId')) {
        obj['itemId'] = ApiClient.convertToType(data['itemId'], 'String');
      }
      if (data.hasOwnProperty('gid')) {
        obj['gid'] = ApiClient.convertToType(data['gid'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('label')) {
        obj['label'] = ApiClient.convertToType(data['label'], 'String');
      }
      if (data.hasOwnProperty('categories')) {
        obj['categories'] = ApiClient.convertToType(data['categories'], ['String']);
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
    }
    return obj;
  }

  /**
   * Read-only
   * @member {String} creationTime
   */
  exports.prototype['creationTime'] = undefined;
  /**
   * This must be your product id used by your own store
   * @member {String} itemId
   */
  exports.prototype['itemId'] = undefined;
  /**
   * Global identifier of this item/product. Read-only
   * @member {String} gid
   */
  exports.prototype['gid'] = undefined;
  /**
   * Human readable title of the item/product
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * Sanitized version of title. Read-only
   * @member {String} label
   */
  exports.prototype['label'] = undefined;
  /**
   * Categories this item belongs to. List of keywords describing the item is also acceptable here.
   * @member {Array.<String>} categories
   */
  exports.prototype['categories'] = undefined;
  /**
   * Full URL that links to the product. e.g. http://yourshop.com/product/123
   * @member {String} url
   */
  exports.prototype['url'] = undefined;



  return exports;
}));


