/**
 * axxell-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AxxellApi) {
      root.AxxellApi = {};
    }
    root.AxxellApi.Store = factory(root.AxxellApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Store model module.
   * @module model/Store
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Store</code>.
   * A store is equivalent to an user account
   * @alias module:model/Store
   * @class
   * @param email {String} Username/email used to login. Set this during registration.
   */
  var exports = function(email) {
    var _this = this;

    _this['email'] = email;




  };

  /**
   * Constructs a <code>Store</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Store} obj Optional instance to populate.
   * @return {module:model/Store} The populated <code>Store</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('apiKey')) {
        obj['apiKey'] = ApiClient.convertToType(data['apiKey'], 'String');
      }
      if (data.hasOwnProperty('password')) {
        obj['password'] = ApiClient.convertToType(data['password'], 'String');
      }
      if (data.hasOwnProperty('salt')) {
        obj['salt'] = ApiClient.convertToType(data['salt'], 'String');
      }
      if (data.hasOwnProperty('storeId')) {
        obj['storeId'] = ApiClient.convertToType(data['storeId'], 'String');
      }
    }
    return obj;
  }

  /**
   * Username/email used to login. Set this during registration.
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * Also known as secret key. Read-only
   * @member {String} apiKey
   */
  exports.prototype['apiKey'] = undefined;
  /**
   * The password required to login. Set this during registration.
   * @member {String} password
   */
  exports.prototype['password'] = undefined;
  /**
   * Internal use
   * @member {String} salt
   */
  exports.prototype['salt'] = undefined;
  /**
   * Also known as access key. Read-only
   * @member {String} storeId
   */
  exports.prototype['storeId'] = undefined;



  return exports;
}));


